default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false

development:
  <<: *default
  compile: true
  dev_server:
    host: localhost
    port: 3035
    https: false

production:
  <<: *default
  compile: false
